name: CI Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Lint Markdown files
      - name: Lint Markdown files
        uses: avto-dev/markdown-lint@v1
        with:
          config: '.markdownlint.json' # optional config file

      # 3. Run ShellCheck on Bash scripts
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v2
        with:
          severity: warning
